SmiteshP/nvim-navic

lua/nvim-navic/init.lua
=> fix: Error after lsp restart

README.md, doc/navic.txt, lua/nvim-navic/init.lua
=> feat: Override options in get_location

README.md, doc/navic.txt, lua/nvim-navic/init.lua
=> feat: silence errors

doc/navic.txt
=> Eliminate duplicate tags from docs

lua/nvim-navic/init.lua
* avoid repeated call to lsp due to multiple triggers
=> perf: Poll lsp on startup

lua/nvim-navic/init.lua
=> perf: (l + h) >> 1

lua/nvim-navic/init.lua
Check is buf valid - prevent error
=> Check is buf valid

lua/nvim-navic/init.lua
=> fix: Handle invalid name and kind output

lua/nvim-navic/init.lua
I have experienced curr being null on line 137, this seems to fix the issue.
=> move curr nil check to for loop

lua/nvim-navic/init.lua
based on pr #43
Uses scope information to determine hierarchy of tree nodes
=> feat: Add support for deprecated SymbolInformation format

lua/nvim-navic/init.lua
=> fix: fix symbol-relation function

lua/nvim-navic/init.lua
Fix https://github.com/utilyre/barbecue.nvim/issues/2.
=> fix: add macro to icon and check list.

README.md, doc/navic.txt, lua/nvim-navic/init.lua
=> fix: Add safe_output option to sanitze special characters

lua/nvim-navic/init.lua
=> fix: bugfix for % substitution not working

README.md, doc/navic.txt, lua/nvim-navic/init.lua
=> feat: Add vim buffer variable to slow down context updates

README.md, doc/navic.txt, lua/nvim-navic/init.lua
- language server attach callback can be async
- explicitly set/get options for callback bufnr to handle this
=> fix: index vim.b options with on_attach bufnr

lua/nvim-navic/init.lua, lua/nvim-navic/lib.lua
* Expose internal lsp releated functions as a library to other potential pllugins
* Also refactor code to make better tree structure from LSP's data
=> Refactor lib

README.md, doc/navic.txt, lua/nvim-navic/init.lua
=> feat: Add click support and integration with nvim-navbuddy

README.md, doc/navic.txt, lua/lualine/components/navic.lua
* Add option to pass navic_opt to lualine component
* Update docs
=> feat: Add color_correction option for lualine component

README.md
=> Fix: Lualine example error

lua/nvim-navic/lib.lua
=> Fix symbol refresh bug
